vars:
  - _variables.manual.yml

stages:
  join:
    cmd: >
      lyscripts data join 
      --inputs '{"source": "data/2021-usz-oropharynx.csv"}'
      --inputs '{"source": "data/2021-clb-oropharynx.csv"}'
      --inputs '{"source": "data/2023-isb-multisite.csv"}'
      --inputs '{"source": "data/2023-clb-multisite.csv"}'
      --inputs '{"source": "data/2024-hvh-oropharynx.csv"}'
      --output-file data/joined.csv
    deps:
      - data/2021-clb-oropharynx.csv
      - data/2021-usz-oropharynx.csv
      - data/2023-clb-multisite.csv
      - data/2023-isb-multisite.csv
      - data/2024-hvh-oropharynx.csv
    outs:
      - data/joined.csv

  enhance:
    cmd: >
      lyscripts data enhance
      --configs _variables.manual.yml
      --input.source data/joined.csv
      --output-file data/enhanced.csv
    deps:
      - data/joined.csv
    params:
      - _variables.manual.yml:
          - modalities
    outs:
      - data/enhanced.csv

  filter-C01:
    cmd: >
      lyscripts data filter
      --input.source data/enhanced.csv
      --output-file data/filtered_C01.csv
      --include
      --column subsite
      --operator contains
      --value C01
    deps:
      - data/enhanced.csv
    outs:
      - data/filtered_C01.csv

  filter-C09:
    cmd: >
      lyscripts data filter
      --input.source data/enhanced.csv
      --output-file data/filtered_C09.csv
      --include
      --column subsite
      --operator contains
      --value C09
    deps:
      - data/enhanced.csv
    outs:
      - data/filtered_C09.csv

  filter-C10:
    cmd: >
      lyscripts data filter
      --input.source data/enhanced.csv
      --output-file data/filtered_C10.csv
      --include
      --column subsite
      --operator contains
      --value C10
    deps:
      - data/enhanced.csv
    outs:
      - data/filtered_C10.csv

  join-filered:
    cmd: >
      lyscripts data join 
      --inputs '{"source": "data/filtered_C01.csv"}'
      --inputs '{"source": "data/filtered_C09.csv"}'
      --inputs '{"source": "data/filtered_C10.csv"}'
      --output-file data/filtered.csv
    deps:
      - data/filtered_C01.csv
      - data/filtered_C09.csv
      - data/filtered_C10.csv
    outs:
      - data/filtered.csv

  reduce:
    cmd: python scripts/reduce.py data/filtered.csv data/reduced.csv
    deps:
      - data/filtered.csv
      - scripts/reduce.py
    outs:
      - data/reduced.csv

  sampling:
    matrix:
      model: [simple]
    cmd: >
      lyscripts --log-level DEBUG sample
      --data.source data/reduced.csv
      --configs _variables.manual.yml
      --configs models/${item.model}/params.ly.yaml
      --sampling.storage-file models/${item.model}/samples.hdf5
      --sampling.history-file models/${item.model}/history.csv
    deps:
      - data/reduced.csv
      - requirements.in
    params:
      - models/${item.model}/params.ly.yaml:
      - _variables.manual.yml:
          - sampling
    outs:
      - models/${item.model}/samples.hdf5
      - models/${item.model}/history.csv:
          cache: false
