---
title: "Probabilistic Model of Bilateral Lymphatic Spread in Head and Neck Cancer"
abstract: |
  We extend the previously published hidden Markov model for lymphatic tumor progression to cover both the ipsi- and contralateral side...
date: last-modified
keywords: 
  - head and neck cancer
  - squamous cell carcinoma
  - lymphatic progression
  - radiotherapy
  - elective nodal target volume
  - probabilistic model
  - hidden Markov model
---
# Introduction

- head and neck cancer spreads through the lymphatic network
- may sometimes spread to contralateral side
- spreads more frequently and to larger extent contralaterally when tumor extends the mid-sagittal line
- we describe a model based on previously published hidden Markov model
- we extend it to cover the contralateral side, too
- naive approach: make two independent models for each side, but that is not supported by the data
- ipsi- and contralateral side are correlated via time of diagnosis, which is correlated with T-category
- tumor extension over mid-sagittal line is modelled as random variable
- spread probabilities from tumor to contralateral LNLs in case of midline extesnion are linear combinations of these probabilities in case of ipsilateral spread and contralateral spread when tumor is clearly lateralized


# Unilateral Model for Lymphatic Progression {#sec-unilateral}

![Directed acyclic graph (DAG) representing the abstract lymphatic network in the head and neck region. Blue nodes are the LNLs' hidden random variables, the red node represents the tumor, and the orange square nodes depict the binary observed variables. Red and blue arcs symbolize the probability of lymphatic spread along that edge during one time-step. The orange arcs represent the sensitivity and specificity of the observational modality (e.g. CT, MRI, pathology, ...).](static/small-graph.png){#fig-small-graph width=60%}

Our first model to predict the lymphatic progression of HNSCC was introduced using Bayesian networks [@pouymayou_bayesian_2019]. We subsequently extended this work to a hidden Markov model (HMM) [@ludwig_hidden_2020]. We will briefly summarize this HMM's formalism before building on it to include the contralateral spread in @sec-ext-to-contra.

We model a patient's state of involvement at an abstract time-step $t$ as a vector of hidden binary random variables:

$$
\mathbf{X}[t] = \begin{pmatrix} X_v[t] \end{pmatrix} \qquad v \in \left\{ 1, 2, \ldots, V \right\}
$$

Here, $V$ is the number of LNLs the model considers. The values a LNL's hidden binary RV may take on are $X_v[t] = 0$ (`False`), meaning the LNL $v$ is healthy or free of metastatic disease, or $X_v[t] = 1$ (`True`), corresponding to some for of tumor presence (i.e., occult or clinical).

Since the state vector $\mathbf{X}[t]$ is $V$-dimensional and binary, there are $2^V$ distinct possible lymphatic involvement patterns, which we enumerate from $\boldsymbol{\xi}_0 = \begin{pmatrix} 0 & 0 & \cdots & 0 \end{pmatrix}$ to $\boldsymbol{\xi}_{2^V} = \begin{pmatrix} 1 & 1 & \cdots & 1 \end{pmatrix}$.

Any hidden Markov model is fully described by three quantities:

1. A starting state $\mathbf{X}[t=0]$ at time $t=0$ just before the patient's tumor formed. In our case, this is always the state where all LNLs are still healthy $\boldsymbol{\xi}_0$.
2. The *transition matrix*
   $$
   \mathbf{A} = \left( A_{ij} \right) = \big( P \left( \mathbf{X}[t+1] = \boldsymbol{\xi}_j \mid \mathbf{X}[t] = \boldsymbol{\xi}_i \right) \big)
   $$
   where the value at row $i$ and column $j$ represents the probability to transition from state $\boldsymbol{\xi}_i$ to $\boldsymbol{\xi}_j$ during the time-step from $t$ to $t+1$. Note that we prohibit self-healing, meaning that during a transition, no LNL may change their state from $X_v[t]=1$ to $X_v[t+1]=0$. This effectively masks large parts of the transition matrix to be zero.
3. Lastly, the *observation matrix*
   $$
   \mathbf{B} = \left( B_{ij} \right) = \big( P \left( \mathbf{Z} = \boldsymbol{\zeta}_j \mid \mathbf{X}[t_D] = \boldsymbol{\xi}_i \right) \big)
   $$
   where in row $i$ and at column $j$ we find the probability to *observe* a lymphatic involvement pattern $\mathbf{Z} = \boldsymbol{\zeta}_j$, given that the true (but hidden) state of involvement at the time of diagnosis $t_D$ is $\mathbf{X}[t_D] = \boldsymbol{\xi}_i$.

The transition matrix $\mathbf{A}$ is parametrized using the spread probabilities of a directed acyclic graph (DAG) that we define as the underlying mechanistic representation of the lymphatic network. An example of such a DAG is shown in @fig-small-graph.

...

$$
P \left( \mathbf{X} \mid \mathbf{Z} \right) = \frac{P \left( \mathbf{Z} \mid \mathbf{X} \right) P \left( \mathbf{X} \right)}{P \left( \mathbf{Z} \right)}
$$ {#eq-uni-bayes-law}

Let us for later use define the matrices $\boldsymbol{\Lambda}$:

$$
\boldsymbol{\Lambda} = P \left( \mathbf{X} \mid \mathbf{t} \right) = \begin{pmatrix}
\boldsymbol{\pi}^\intercal \cdot \mathbf{A}^0 \\
\boldsymbol{\pi}^\intercal \cdot \mathbf{A}^1 \\
\vdots \\
\boldsymbol{\pi}^\intercal \cdot \mathbf{A}^{t_\text{max}} \\
\end{pmatrix}
$$ {#eq-lambda-matrix}

The $n$-th row in this matrix corresponds to the distribution over hidden states after $t=n-1$ time-steps.


# Extension to a Bilateral Model {#sec-ext-to-contra}

A naive approach to model the contralateral lymphatic spread would be to simply employ two independent unilateral models as introduced in @sec-unilateral. During training, one could even enforce some shared parameters between these two models, like the parameterization of the distributions over diagnose times or the spread among the LNLs. Additionally, we could think of an approach to incorporate the primary tumor's mid-sagittal extension as a risk factor.

However, this approach lacks a way to describe the correlation between ipsi- and contralateral involvement. This is displayed in @tbl-contra and shows how often the contralateral LNLs I, II, III, and IV were involved, given all possible combinations of midline extension, T-category, and ipsilateral LNL III involvement. Unsurprisingly, the prevalence for contralateral involvement is consistently higher when the tumor extends over the mid-sagittal line or is of later T-category. But it is also more frequent when the ipsilateral side shows more severe involvement, which is here shown via the surrogate LNL III.

{{< embed notebooks/data.qmd#tbl-contra >}}

Thus, we attempt to extend the formalism in @sec-unilateral in such a way that the model's ipsi- and contralateral side evolve synchronously. To achieve that, we start by writing down the posterior distribution of involvement an analogy to @eq-uni-bayes-law, which is now a joint probability of an involvement $\mathbf{X}^\text{i}$ ipsilaterally *and* an involvement $\mathbf{X}^\text{c}$ contralaterally, given a diagnosis of the ipsilateral LNLs $\mathbf{Z}^\text{i}$ and of the contralateral ones $\mathbf{Z}^\text{c}$:

$$
P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \mid \mathbf{Z}^\text{i}, \mathbf{Z}^\text{c} \right) = \frac{P \left( \mathbf{Z}^\text{i}, \mathbf{Z}^\text{c} \mid \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \right) P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \right)}{P \left( \mathbf{Z}^\text{i}, \mathbf{Z}^\text{c} \right)}
$$

The likelihood of the diagnoses given a hidden state simply factorise: $P \left( \mathbf{Z}^\text{i}, \mathbf{Z}^\text{c} \mid \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \right) = P \left( \mathbf{Z}^\text{i} \mid \mathbf{X}^\text{i} \right) \cdot P \left( \mathbf{Z}^\text{c} \mid \mathbf{X}^\text{c} \right)$. And the two factors are contained in the observation matrices $\mathbf{B}^\text{i}$ and $\mathbf{B}^\text{c}$.

The term representing the model's prior probability of hidden involvement does not factorize. However, if we assume that lymphatic spread typically does not cross the mid-sagittal line, we can write it as a factorising sum:

$$
\begin{aligned}
P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \right) &= \sum_{t=0}^{t_\text{max}} P(t) \cdot P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c} \mid t \right) \\
&= \sum_{t=0}^{t_\text{max}} P(t) \cdot P \left( \mathbf{X}^\text{i} \mid t \right) \cdot P \left( \mathbf{X}^\text{c} \mid t \right)
\end{aligned}
$$ {#eq-bilateral-marginal}

This assumption makes intuitive sense: The two sides of the lymphatic network in a typical patient are approximately mirror images of each other. Thus, no major vessels cross the mid-sagittal line. There may, however, be diffusion of lymph fluid accross this line or bulky involvement that redirects lymphatic drainage significantly.

Using this assumption along with @eq-lambda-matrix, we can write the above distribution algebraically as a product:

$$
P \left( \mathbf{X}^\text{i} = \boldsymbol{\xi}_n, \mathbf{X}^\text{c} = \boldsymbol{\xi}_m \right) = \left[ \boldsymbol{\Lambda}^\intercal_\text{i} \cdot \operatorname{diag} P(\mathbf{t}) \cdot \boldsymbol{\Lambda}_\text{c} \right]_{n,m}
$$ {#eq-bilateral-marginal-algebra}


## Incorporating Midline Crossing

To account for the increased prevalence of involvement on the contralateral side when the tumor is not clearly lateralized anymore, we also model the tumor's extension over the mid-sagittal line as a binary random variable. It starts lateralized and at every time-step there is a finite probability $p_\epsilon$ that the tumor grows over the symmetry plane of the patient.

Technically, the introduction of this additional random variable doubles the space of the hidden states and therefore quadruples the size of the transition matrix $\mathbf{A}$. However, since we assume no correlation between the tumor's lateralization and the metastases in the LNLs, we can evolve the two parts separately.

The probabilities to find a patient with a clearly lateralized tumor or one that extends over the mid-sagittal line after $t$ time-steps are then given by

$$
\begin{aligned}
P(\epsilon = \texttt{False} \mid t) &= (1 - p_\epsilon)^t \\
P(\epsilon = \texttt{True} \mid t) &= 1 - (1 - p_\epsilon)^t
\end{aligned}
$$

To get the joint probability over the ipsi- and contralateral hidden states, as well as the state of the tumor's midline extension $P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c}, \epsilon \right)$, we simply add the above terms to the marginalization in @eq-bilateral-marginal:

$$
P \left( \mathbf{X}^\text{i}, \mathbf{X}^\text{c}, \epsilon \right) = \sum_{t=0}^{t_\text{max}} P(t) \cdot P(\epsilon \mid t) \cdot P \left( \mathbf{X}^\text{i} \mid t \right) \cdot P \left( \mathbf{X}^\text{c} \mid t \right)
$$

Again, this can be written algebraically, by defining the vector $P(\mathbf{t}, \epsilon) = P(\mathbf{t}) \cdot P(\epsilon \mid \mathbf{t})$, to achieve the same form as in @eq-bilateral-marginal-algebra:

$$
P \left( \mathbf{X}^\text{i} = \boldsymbol{\xi}_n, \mathbf{X}^\text{c} = \boldsymbol{\xi}_m, \epsilon \right) = \left[ \boldsymbol{\Lambda}^\intercal_\text{i} \cdot \operatorname{diag} P(\mathbf{t}, \epsilon) \cdot \boldsymbol{\Lambda}_\text{c} \right]_{n,m}
$$

In @fig-midext-evo, we visualize how the prior distribution over diagnose times $P(t)$, the conditional probability of midline extension $P(\epsilon \mid t)$, and their joint $P(\epsilon, t)$ evolve over the course of a patient evolution.

{{< embed notebooks/model.qmd#fig-midext-evo >}}


## Parameter Symmetries {#sec-params-symmetry}

In general, the matrices $\boldsymbol{\Lambda}_\text{i}$ and $\boldsymbol{\Lambda}_\text{c}$ could be parameterized using a disjoint set of parameters. I.e., the ipsi- and contralateral spread rates are entirely different. However, using two sensible assumptions, we can reduce the parameter space by sharing some parameters between the sides:

1. We assume the spread *among* the LNLs to be same on both sides. It is reasonable to assume the lymphatic system is symmetric. Thus, the spread rates from one LNL to the other should be symmetric, too. Formally, this means \
   $$
   \begin{aligned}
   b_v^\text{c} &\neq b_v^\text{i} \\
   t_{rv}^\text{c} &= t_{rv}^\text{i}
   \end{aligned}
   $$ {#eq-symmetries}
   for all $v \leq V$ and $r \in \operatorname{pa}(v)$.
2. The tumor's spread to the contralateral side in case of an extension over the midline is larger than if it was clearly lateralized, but smaller than its spread to the ipsilateral side. This assumption stems from a simple thought experiment: Consider moving the tumor from a clearly lateralized position accross the mid-sagittal plane to its mirror position. In the beginning we would have $b_v^\text{c} < b_v^\text{i}$, while in the end, the situation is reversed. If a tumor extends over the mid-sagittal line, its contralateral spread rate can be expected to be in between these two extremes. We encode this in a *mixing parameter* $\alpha$ that captures a "degree of asymmetry": \
   $$
   b_v^\text{c,e} = \alpha \cdot b_v^\text{i} + (1 - \alpha) \cdot b_v^{\text{c},\centernot{\text{e}}}
   $$ {#eq-mixing}


## Tumors Extending Over the Mid-Sagittal Line {#sec-midline}

- higher prevalence of contralateral involvement when tumor crosses the mid-sagittal plane
- but still lower than on ipsilateral side
- spread to contralateral side in case of midline extension may be describes as linear combination of ipsi- and contralateral spread in case of no midline extension.
- only one additional "mixing parameter" $\alpha$
- tumor's midline extension modelled as a binary RV (lateralized or crossing/extending)


# Detailed Data on Lymphatic Involvement

- describe origin of data
- why is this data special?
- mention [LyProX](https://lyprox.org)
- visualize data, e.g. using upsetplots

To train our models, we used detailed tabular data specifying the lymphatic involvement of individual patients on a per LNL basis.

{{< embed notebooks/data.qmd#fig-data-upset >}}


# Methods

We compared three different aprroaches to modelling the contralateral involvement in OPSCC:

1. A naive model of the contralateral side only. Neither the patterns of ipsilateral involvement, nor the information on whether the patients' tumors crossed the mid-sagittal line enter this model.
2. The bilateral model as introduced in the sections up to and including @sec-params-symmetry. The involvement patterns of both sides enter this model, but not whether the tumors extended the midline.
3. An additional bilateral model that tracks the midline extension of the patients' tumors as a random variable. This includes the formalism introduced up to and including @sec-midline. In contrast to the other two models, it does consider the reported midline extension in the data to attempt a more accurate prediction of the risk for contralateral occult disease.

- all models initialized with the same settings
  - same graph
  - same data
  - same distributions over diagnose time
- parameter samples were drawn for all three models:
  - the sampling used {{< var sampling.walkers_per_dim >}} walkers per parameter space dimension.
  - Every {{< var sampling.check_interval >}} steps, convergence was checked
  - convergence was reached when two criteria were met:
      1. the relative difference between subsequent autocorrelation estimates of the chain does not change more than {{< var sampling.rel_thresh |  >}}.
      2. the autocorrelation estimate of the chain drops below the length of the chain divided by {{< var sampling.trust_fac >}}.
  - after convergence, {{< var sampling.nsteps >}} samples (from the parallel walkers) were drawn that were spaced {{< var sampling.thin >}} steps apart, resulting in `num params x {{< var sampling.walkers_per_dim >}} x {{< var sampling.nsteps >}}` parameter samples.

For every model, we compare the predicted prevalence of a certain scenario to how often this scenario is seen in the data. The considered scenarios are choosen to test if the models can take into account T-category, the correlation of ipsi- and contralateral involvement, and the primary tumor's lateralization (whether or not it extends over the mid-sagittal line).

- [ ] list and describe the scenarios


# Results

{{< embed notebooks/results.qmd#fig-burnin-history >}}

@Fig-burnin-history is only a temporary placeholder for now.

## Prevalence Comparisons

Below we compare the predicted with the observed prevalence of some involvement patterns.

{{< embed notebooks/results.qmd#fig-prevalences >}}


## Parameter Estimates

{{< embed notebooks/results.qmd#tbl-midline-params >}}

The predicted prevalence of midline extension for early T-category tumors is <!-- insert computational code later -->. For a late T-category tumor, it is <!-- insert computational code later -->.

In the data, the prevalence of midline extension for early T-category tumors is <!-- insert computational code later -->. For late T-category tumors it is <!-- insert computational code later -->.

- Discrepancy between data and model is due to late T-stage's time prior
- still tied to other parameters
- cannot fully represent spread of midline extension and also represent spread params
